name: PublishğŸš€

on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET ğŸ“
        uses: actions/setup dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore ğŸ›Ÿ
        run: dotnet restore ./BeanJournal_BackEnd.sln

      - name: Build ğŸ¢
        run: dotnet build ./BeanJournal_BackEnd.sln --configuration Release --no-restore

      - name: Publish ğŸ“¢
        run: dotnet publish ./BeanJournal_BackEnd.sln --configuration Release --no-build
